dist: bionic

services:
  - docker

before_scripts:
  - make version

script:
  - make lint
  - make images.test
  - make images.build

deploy:
  provider: script
  script: make images.push
  on:
    tags: true

notifications:
  email: false
