version: '2'

services:

  hadolint:
    image: hadolint/hadolint:v1.17.6-alpine
    volumes:
      - .:/test
      - .hadolint.yml:/.hadolint.yaml
    command: find /test -type f -name Dockerfile -exec hadolint {} +
