version: '3'

services:

  nginx:
    image: nginx:1.17-alpine
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/site.conf:/etc/nginx/conf.d/site.conf
    restart: on-failure
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  php:
    build:
      context: ..
    environment:
      PHP_SENDMAIL_HOST: mailhog
      PHP_SENDMAIL_PORT: 1025
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
      - mailhog
